### PR TITLE
Various fixes and improvements

### PR DESCRIPTION
**Pull request by matthijskooijman**
This PR adds some new options which make slsnif a bit more useful to analyze a serial protocol (such as a hexdump-style output and better batching of multiple characters seen in quick succession). To implement these, I had to refactor some of the code a bit. While I was there, I also fixed a bug and some warnings.

### CODE REVIEW

**Comment by aeruder** [comment]
Sorry! 100% didn't notice this pull request. I have added a note at the top of my repository pointing towards yours as I'm not that interested in maintaining this. Also happy to delete my repo (and then yours will become its own thing unaffiliated as a fork on github). Thoughts?

**Comment by aeruder** [comment]
Also added you as a collaborator on this one if you'd rather go that route!

**Comment by matthijskooijman** [comment]
To be honest, I'm not that interested in maintaining this either (I can't even quite remember what I used slsnif for last year). However, I've accepted your invitation to be a collaborator, so I'll keep an eye on any issues and PRs here (if time permits). For now, let's merge this PR and remove the link to my repo at the top?

**Comment by aeruder** [comment]
Sounds perfect, I'll see what I can do about the issue that just popped up too.

**Pull request merged**
